### ISSUE TITLE
DataSummary ET 唯一值计算不应该使用approx_count_distinct

### ISSUE THREAD

**Issue by hellozepp** [byzer-org/byzer-extension#19]
目前代码中唯一值比例计算，使用的是approx_count_distinct，该算法存在一定的误差，不符合唯一值计算要求。

- 需要确认一下调用时不传入标准误差的情况下默认值是多少，是否还依然存在误差。

- 增加条件参数，支持指定approx_count_distinct误差比例，默认通过count（distinct）精确求值，不使用approx_count_distinct

**Comment by ZhengshuaiPENG** [comment]
PR： https://github.com/byzer-org/byzer-extension/pull/22
