### ISSUE TITLE
【mllib】新增模式分布ET插件

### ISSUE THREAD

**Issue by hellozepp** [byzer-org/byzer-extension#27]
模式分布包含的指标 （只统计字符类型的）:
    - 模式
    - 备用
    - 计数
    - 百分比
 > 约束： 模式个数超过1000个，则截断，只取1000个模式。

## 模式分布统计规则
<p style="word-break: break-word; margin: 0px 0px 1em; padding: 0px; list-style: none; line-height: inherit; color: rgb(24, 43, 80); font-family: &quot;Microsoft YaHei&quot;, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">规则1： 字母 （区分大小写，ABcd）（映射）-&gt; AAaa</p><p style="word-break: break-word; margin: 0px 0px 1em; padding: 0px; list-style: none; line-height: inherit; color: rgb(24, 43, 80); font-family: &quot;Microsoft YaHei&quot;, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">规则2：中文字符（中文）（映射） -&gt; AA</p><p style="word-break: break-word; margin: 0px 0px 1em; padding: 0px; list-style: none; line-height: inherit; color: rgb(24, 43, 80); font-family: &quot;Microsoft YaHei&quot;, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">规则3： 数字  （映射）-&gt; 9</p><p style="word-break: break-word; margin: 0px 0px 1em; padding: 0px; list-style: none; line-height: inherit; color: rgb(24, 43, 80); font-family: &quot;Microsoft YaHei&quot;, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">规则4： 特殊符号（.#/*...）  （不变）-&gt; 特殊符号（.#/*...）</p><p style="word-break: break-word; margin: 0px 0px 1em; padding: 0px; list-style: none; line-height: inherit; color: rgb(24, 43, 80); font-family: &quot;Microsoft YaHei&quot;, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br style="word-break: break-word;"></p><p style="word-break: break-word; margin: 0px 0px 1em; padding: 0px; list-style: none; line-height: inherit; color: rgb(24, 43, 80); font-family: &quot;Microsoft YaHei&quot;, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">示例：</p><div class="tox-clear-float" style="word-break: break-word; margin: 0px; padding: 0px; line-height: inherit; color: rgb(24, 43, 80); font-family: &quot;Microsoft YaHei&quot;, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div style="word-break: break-word; margin: 0px; padding: 0px; line-height: inherit;"><div style="word-break: break-word; margin: 0px; padding: 0px; line-height: inherit;"><div style="word-break: break-word; margin: 0px; padding: 0px; line-height: inherit;"><div style="word-break: break-word; margin: 0px; padding: 0px; line-height: inherit;"><div style="word-break: break-word; margin: 0px; padding: 0px; line-height: inherit;"><div style="word-break: break-word; margin: 0px; padding: 0px; line-height: inherit;"><div style="word-break: break-word; margin: 0px; padding: 0px; line-height: inherit;"><div style="word-break: break-word; margin: 0px; padding: 0px; line-height: inherit;"><div style="word-break: break-word; margin: 0px; padding: 0px; line-height: inherit;"><div style="word-break: break-word; margin: 0px; padding: 0px; line-height: inherit;"><div style="word-break: break-word; margin: 0px; padding: 0px; line-height: inherit;"><div style="word-break: break-word; margin: 0px; padding: 0px; line-height: inherit;"><div style="word-break: break-word; margin: 0px; padding: 0px; line-height: inherit;"><div style="word-break: break-word; margin: 0px; padding: 0px; line-height: inherit;"><div style="word-break: break-word; margin: 0px; padding: 0px; line-height: inherit;"><div style="word-break: break-word; margin: 0px; padding: 0px; line-height: inherit;"><div style="word-break: break-word; margin: 0px; padding: 0px; line-height: inherit;"><div class="scroll_table" style="word-break: break-word; margin: 0px; padding: 0px; width: 1262px; max-width: 100%; overflow-x: auto; line-height: inherit;">

字符串（单词等） | 模式 | 模式（备用）
-- | -- | --
Abc.中文字符#123.01/abc中文 | Aaa.AAAA#999.99/aaaAA | Aa(2).A(4)#9(3).9(2)/a(3)A(2)

</div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div>

## 交互设计示例
<img width="852" alt="image" src="https://user-images.githubusercontent.com/20615623/178434103-b7e40f57-12d6-4497-9024-9d94f86a62c1.png">

**Comment by ckeys** [comment]
规则 1 确定么？ 我看 SAS 的规则 1 是大小写分开？需求确定就确定下去了哦？

**Comment by ZhengshuaiPENG** [comment]
- 数据的输入：
   - 表(db.tablename)
   - 只应用在 string 列
- 数据的输出：以表的形式进行返回，key- value 的格式

|Col_Name | 模式分布|
|--|--|
|字段名| json_string |

```json
{
"列模式分布":[
    ["模式": "AAA,AA",
    "备用": "A(3),A(2)",
    "计数":15,
    "百分比":0.15
    ],
    ["模式": "AAA,AA",
    "备用": "A(3),A(2)",
    "计数":15,
    "百分比": 0.15
    ],
    ["模式": "AAA,AA",
    "备用": "A(3),A(2)",
    "计数": 15,
    "百分比": 0.15
    ]],
"模式总计数":1000,
"limit": 500
}
```
1.  当出现 exception case，如应用到其他类型的列是，该返回中，列模式分布为空，模式总计数值为 0
2. 期望"列模式分布" 结果是受 limit 参数控制，默认值可以设置成 500，该值设置为 <0 的时候为全集,对应返回值”limit"
 (在获取到指定行数的模式分布返回时 （比如1000），应该是以**计数** 列倒序，相当于对 **计数列** 取 top（1000）)


  对于规则的补充：
- 除拉丁语字母外的所有字母，都和规则二中的中文处理一致： `A`, 包括中文，一个字符为一个大写的 `A`

对性能的要求：分布式处理（待确认）

**Comment by ckeys** [comment]
字段更改如下，方便调用方获取

Col_Name -> colName
模式分布 -> patternDistribution
列模式分布-> colPatternDistribution
模式->pattern
备用->alternativePattern
计数->count
百分比->ratio
模式总计数"->totalCount
limit->limit

**Comment by hellozepp** [comment]
{
"colPatternDistribution":[
    {"pattern": "AAA,AA",
    "alternativePattern": "A(3),A(2)",
    "count":15,
    "ratio":0.15
    },
    {"pattern": "AAA,AA",
    "alternativePattern": "A(3),A(2)",
    "count":15,
    "ratio":0.15
    },
    {"pattern": "AAA,AA",
    "alternativePattern": "A(3),A(2)",
    "count":15,
    "ratio":0.15
    }],
"totalCount":1000,
"limit": 500
}

**Comment by ckeys** [comment]
模式最多保留1000个字符

**Comment by hellozepp** [comment]
模式总计数统计有问题，当前为：统计所有模式串个数模式个数最多的模式计数
应该改为：统计去重后的模式条数
