### ISSUE TITLE
Data Summary ET Improvement Epic

### ISSUE THREAD

**Issue by ZhengshuaiPENG** [byzer-org/byzer-extension#31]
需要整理近期的在 Data Summary ET 上的一些fix以及功能描述，预计在 2.3.2 版本中进行 Release

**Comment by ckeys** [comment]
https://github.com/byzer-org/byzer-extension/pull/26 ：
- 修复均值的最终结果，没有根据 round_at 转换保留的小数点位数 【BUG】
https://github.com/byzer-org/byzer-extension/pull/22/files ：
 - 增加非数字类型的列的 mode 值计算 【新需求】 
 - String 数据长度更改 【更改需求】
 - 增加 approx 计算唯一值，设置 approx 计算开关，即支持精确计算（大数据量会有数据瓶颈），同时支持 approx 计算 【新需求】
 https://github.com/byzer-org/byzer-extension/pull/20/files
- 在计算 Quantile 数值的时候，支持对空值的过滤 【需求不明确 / BUG】

https://github.com/byzer-org/byzer-extension/pull/28
-  百分比展示，保留 round_at + 2 位 【更改需求】
-  重新实现 Quantile 计算，支持精准计算 Quantile 值，使用的时候注意数据性能瓶颈的问题 【需求】
