### ISSUE TITLE
【ET】新增唯一标识符算子

### ISSUE THREAD

**Issue by hellozepp** [byzer-org/byzer-extension#34]
## 需求描述
我现在有一张表，需要对表生成一列全局唯一的值，可以选择替换现有列或者创建新列。
唯一值生成规则：唯一值为从1开始的自增ID，（sas规则：自增ID+01）

参考文档：https://documentation.sas.com/doc/en/dprepcdc/2.4/datastudioadv/n0ooiqdt13mn6sn1ejbeyv4ech8d.htm

## 测试用例
<byte-sheet-html-origin data-id="B5CrveWac5-1658824756391" data-version="3" data-is-embed="true">

havana_id | a | b
-- | -- | --
1 | aaa | bbb
2 | aaa | bbb
3 | aaa | bbb
1 | aaa | bbb
2 | aaa | bbb
3 | aaa | bbb
</byte-sheet-html-origin>

## 期望的结果
如果是替换现有列，选择了havana_id这一列，结果：

<byte-sheet-html-origin data-id="B5CrveWac5-1658824756391" data-version="3" data-is-embed="true">

havana_id | a | b
-- | -- | --
1 | aaa | bbb
2 | aaa | bbb
3 | aaa | bbb
4 | aaa | bbb
5 | aaa | bbb
6 | aaa | bbb
</byte-sheet-html-origin>

如果是创建新列，设置了新列的列名为Unique_ID，结果：
<byte-sheet-html-origin data-id="B5CrveWac5-1658824756391" data-version="3" data-is-embed="true">

Unique_ID | havana_id | a | b 
-- |  -- | -- | --
1 | 1 | aaa | bbb
2 | 2 | aaa | bbb
3 | 3 | aaa | bbb
4 | 1 | aaa | bbb
5 | 2 | aaa | bbb
6 | 3 | aaa | bbb
</byte-sheet-html-origin>

> 注意，如果创建新列的列名与现有列名冲突，应报错提示

**Comment by hellozepp** [comment]
@fishcus 需要帮忙确认的技术细节：
1. spark sql可以通过row_number over window 实现，但如果数据量（千万级别）过大窗口函数性能较差，是否可以改用ET通过RDD来处理？
2. RDD算子的zipWithIndex算子是否需要提前做parallel或者repartition处理？
3. zipWithIndex生成的index是int还是long类型？已确认为long

**Comment by fishcus** [comment]
问题1,2：是可以通过借助ET，使用RDD的zipWithIndex来做，zipWithIndex这个算子本身不需要额外做parallel或者repartition，使用的是parent RDD的partition特征，如果parent RDD的partition不理想，可以前置去做repartition；

**Comment by fishcus** [comment]
问题1,2：是可以通过借助ET，使用RDD的zipWithIndex来做，zipWithIndex这个算子本身不需要额外做parallel或者repartition，使用的是parent RDD的partition特征，如果parent RDD的partition不理想，可以前置去做repartition，这个操作是按需的；
问题4：zipWithIndex算子操作后全局有序
问题5：zipWithIndex本身不支持自定义start index，spark实现里面默认就是0，从1开始计算的话，可以在zipWithIndex之后再对这个id列做+1操作？或者自己定义一个类似ZippedWithIndexRDDV2，再或者就是向spark 提pr了

**Comment by hellozepp** [comment]
问题5，采用了自己定义一个RDD的方案

**Comment by allwefantasy** [comment]
> 
这个可以用 acuumulator 来完成计数么？

**Comment by hellozepp** [comment]
效果要比acuumulator好，是现在多个分区获取iterator获取迭代器长度，然后根据分区和各分区条数计算一个起始index，然后在每个分区并行计算每条数据的index
