### ISSUE TITLE
【DataSummary】剖析支持decimal类型

### ISSUE THREAD

**Issue by hellozepp** [byzer-org/byzer-extension#40]
如下图所示，fare列为decimal类型，且存在较长小数位的情况，剖析结果没有保留2位小数：
![origin_img_v2_d9704d96-ccc3-4cd1-9f95-9473bee8b53g](https://user-images.githubusercontent.com/20615623/182275677-1ee93c32-e9b0-4415-98c0-e2562c9ab71e.jpg)
而实际中位数结果为需要结果为14.1542，需要保留2位小数。

**任务描述**

  目前titanic_train1数据集中存在decimal格式的字段fare，该格式无法计算均值，中位数，标准差，标准误差和数据长度，众数，最大，最小没有做保留处理直接返回结果。
另外，fare字段设置为double格式时，计算值展示了六位小数，即没有做保留处理直接返回结果，需要一同排查。

**任务目标**

  支持剖析decimal格式字段并正常输出保留小数点后两位的计算值

**Comment by ZhengshuaiPENG** [comment]
**reproduce step**：
1. 上传titanic 导入至 mysql 数据库， fare 列是 decimal 类型，此时加载至byzer后无法计算 均值，中位数等
2. 将 fare 列在数据库中手动改成 double 类型，加载至 byzer
3. 然后 fare 可以进行 均值，中位数，标准差，标准误差和数据长度 等计算，但计算结果没有保留两位小数

**预期**：
- DataSummary 支持 decimal 的列，用于支持全 DataSummary 中的算子， 即上述步骤中 fare 列为 decimal时，可以进行计算
且计算结果小数位保持两位 `xxx.yy`，百分位也保持两位`xx.yy%`
- 手动将 fare 列在 mysql 中改为 double 类型，结果也同时保留小数位两位，百分位保持两位
