### ISSUE TITLE
【DataSummary】最大长度最小长度没有应该显示空字符串不应该显示0

### ISSUE THREAD

**Issue by hellozepp** [byzer-org/byzer-extension#41]
![image](https://user-images.githubusercontent.com/20615623/182285121-d4c88bbe-d551-4a28-912e-30a6522caeb2.png)
任务描述：

  目前运行剖析对于数值类型的字段展示最大，最小计算结果为0，实际上是不对数值类型的字段做这两个计算

任务目标：

  对不计算的地方统一展示空，而不是0或者NULL

**Comment by ZhengshuaiPENG** [comment]
最大长度和最小长度只对字符串类型（`string`， `varchar`，`char`）进行计算，返回具体的计算数字，其他的数据类型返回为空字符串 `""`
![image](https://user-images.githubusercontent.com/11333496/182324052-32221eeb-b64e-47a4-ad31-835fccafea8f.png)



字段类型可参考：
![image](https://user-images.githubusercontent.com/11333496/182323904-5ab7c2f4-c97c-41fa-9baf-91ee6a6fbeb9.png)
