### ISSUE TITLE
【DataSummary】运行剖析众数实现方式调整

### ISSUE THREAD

**Issue by hellozepp** [byzer-org/byzer-extension#42]
任务描述：

  当前众数的实现方式为多个众数取第一个展示，更改为众数超过一个时不展示众数，如果唯一值为100%（即所有数的frequency都为1）的字段没有众数

任务目标：

  运行剖析结果中，众数有且仅有一个时才展示

**Comment by ZhengshuaiPENG** [comment]
关于众数的说明：https://www.shuxuele.com/mode.html

当一个列的众数计算结果超出一个时（多众数情况），我们以下述为例

```
1, 1, 2, 2, 3, 3, 4, 4, 5, 5
```
众数结果为

```
1, 2, 3, 4, 5
```

那么有三种返回的方式：
1. 取第一个众数进行返回， 即 `1`
2. 返回全部众数的 list, 即 `[1, 2, 3, 4, 5]` 
3. 全部不返回，即返回空字符串 `""`

对于 summary et 的实现来讲，可以通过参数来控制当出现多众数的情况上述三种不同的返回方式，其中默认的返回方式为 全部不返回
