### ISSUE TITLE
模式分布优化

### ISSUE THREAD

**Issue by hellozepp** [byzer-org/byzer-extension#60]
现状：
目前5g数据执行需要7分钟，需要优化。

资源情况：
1*driver (5c16g) + 6* excutor (5c16g)

需求：
优化10G（2000万行，15列）的JuiceFS文件的模式分布，5分钟内执行完成。

**Comment by fishcus** [comment]
数据集，分片数 6， row count 700多w
<img width="1646" alt="image" src="https://user-images.githubusercontent.com/13731531/188818353-2f2c18b5-db79-4d00-87e4-8f203d95c99d.png">


3个 ET 串行跑 耗时40s
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/13731531/188815780-48f881bc-cadd-4743-afdc-238c7bcc90cc.png">

3个 ET 并行跑 耗时 18s
<img width="1659" alt="image" src="https://user-images.githubusercontent.com/13731531/188817960-01019f3f-2af4-4124-ab83-1a86e475e22f.png">

**Comment by hellozepp** [comment]
@fishcus 10G的数据集试一下

**Comment by fishcus** [comment]
<img width="1658" alt="image" src="https://user-images.githubusercontent.com/13731531/188832318-43fdd78a-093f-4e90-968c-e252db3d10ab.png">

**Comment by fishcus** [comment]
对SQLPatternDistribution中提交job的进行并行化操作
耗时为137s

<img width="1645" alt="image" src="https://user-images.githubusercontent.com/13731531/188836346-efd82841-54cb-4bc0-a39c-42fb01f552eb.png">
